version: '3'
services:
  terraria:
    image: ryandw11/terraria:latest
    container_name: terraria_server
    ports:
      - "7777:7777"
    environment:
      - WORLD_NAME=${WORLD_NAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
    volumes:
      - ./config:/config
      - ./world:/root/.local/share/Terraria/Worlds
      - ./plugins:/plugins
      - ./tshock:/tshock
    stdin_open: true
    tty: true
    restart: always
