name: Validar Servidor
on: [push]
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verificar archivos criticos
        run: |
          test -f docker-compose.yml && echo "Docker OK"
          test -f config/serverconfig.txt && echo "Config OK"
